### PR TITLE
Fix transformers deprecation warnings

### LINKED ISSUE #601: Gradle 6.6.1 still reports shadowJar has a forward-incompatibility with Gradle 7.0
This is to report that, despite all the good work to address #530, there seems to be a leftover `Property 'transformers.$1.data' is not annotated with an input or output annotation`.

### Shadow Version

```groovy
id 'com.github.johnrengelman.shadow' version '6.1.0'
```

### Gradle Version

```
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_265 (Private Build 25.265-b01)
OS:           Linux 5.4.0-47-generic amd64
```

### Expected Behavior

No forward-incompatibility with Gradle 7.0.

### Actual Behavior

```sh
$ ./gradlew --debug assemble
...
[LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :my:shadowJar UP-TO-DATE
[DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :my:shadowJar' started
[DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':my:shadowJar' into context took 0.0 secs.
[WARN] [org.gradle.internal.featurelifecycle.LoggingDeprecatedFeatureHandler] Property 'transformers.$1.data' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.6.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
[DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot inputs and outputs before executing task ':my:shadowJar'' started
...
```

### Gradle Build Script(s)

```groovy
plugins {
...
    id 'com.github.johnrengelman.shadow' version '6.1.0' apply false
...
}
...
project(':my') {
...
    apply plugin: 'com.github.johnrengelman.shadow'
...
    shadowJar {
        mergeServiceFiles()
        append('my.conf')
    }
...
}
```

### PR DESCRIPTION
**Pull request by helfper**
This PR annotates transformers' configuration fields as inputs to solve the deprecation warnings.

Closes #601 
Fixes the remaining warnings in #530 (only the first one was addressed in #569)

Caveats:
* I've marked `PropertiesFileTransformer.keyTransformer` as internal, while I believe it should also be an input. Just annotating it with `@Input` will cause Gradle to eagerly calculate its value (passing `null` as parameter) which is not desirable. The solution may be wrapping the closure with `Property<>`, but I'm not totally sure. At least one other plugin in a similar situation seem to have gone with internal as well (https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy#L76)
* Had to comment out the test for `ManifestResourceTransformer`, because as far as I can see, that transformer has been broken since `JarOutputStream` was replaced by `ZipOutputStream` in version 0.9.0/1.0.0. This is independent of the changes in this PR and should be solved when this is released upstream: https://github.com/apache/ant/pull/145

### CODE REVIEW

File: src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.groovy [hunk 1]
```diff
@@ -34,34 +36,48 @@ import java.text.SimpleDateFormat
  * @author John Engelman
  */
 class ApacheNoticeResourceTransformer implements Transformer {
+
+    @Input
     Set<String> entries = new LinkedHashSet<String>()
```
Comment (wolfs) [inline src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.groovy:41]:
```suggestion
    private Set<String> entries = new LinkedHashSet<String>()
```

It seems like this is modified while running the transformer, so I think this should be made private.

File: src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.groovy [hunk 2]
```diff
@@ -34,34 +36,48 @@ import java.text.SimpleDateFormat
...
 
+    @Input
     Map<String, Set<String>> organizationEntries = new LinkedHashMap<String, Set<String>>()
```
Comment (wolfs) [inline src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/ApacheNoticeResourceTransformer.groovy:44]:
```suggestion
    private Map<String, Set<String>> organizationEntries = new LinkedHashMap<String, Set<String>>()
```

It seems like this is modified while running the transformer, so I think this should be made private.

File: src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.groovy [hunk 3]
```diff
@@ -33,8 +37,12 @@ import org.codehaus.plexus.util.IOUtil
  * @author John Engelman
  */
 public class IncludeResourceTransformer implements Transformer {
+
+    @InputFile
+    @PathSensitive(PathSensitivity.NAME_ONLY)
```
Comment (wolfs) [inline src/main/groovy/com/github/jengelman/gradle/plugins/shadow/transformers/IncludeResourceTransformer.groovy:42]:
```suggestion
    @PathSensitive(PathSensitivity.NONE)
```

I think the name doesn't matter here.

**Review by wolfs — COMMENTED** [review]
I left some comments.

I think this looks good and fixes the deprecation warnings with Gradle 7.0 in the production code.

**Comment by helfper** [comment]
@wolfs Thanks for reviewing the PR. I've applied your suggestions, but I'm fine if #646 gets merged instead of this. I like how you added the deprecation checks globally.
